manifest_path: target/manifest.json
output_dir: .
selectors_output_file: output/selectors.yml
jobs_output_file: jobs.yml
selector:
  method: fqn
  group_by_dependencies: true
  exclude_tags: []
  exclude_models: []
  exclude_paths: []
  include_path_groups: []
  include_freshness_selectors: true
  include_parent_sources: true
  prefix_order: []
  path_grouping_level: 1
  min_models_per_selector: 1
  selector_prefix: automatically_generated_selector
  preserve_manual_selectors: true
job:
  account_id: null
  project_id: null
  environment_id: null
  dbt_version: ''
  threads: 8
  target_name: prod
  timeout_seconds: 0
  cron_schedule: 0 */6 * * *
  generate_docs: false
  run_generate_sources: false
  job_name_prefix: dbt
deployment:
  deploy_branch: main
  require_dbt_jobs_as_code: true
  dbt_project_path: .
