"""Prove DAG regeneration is idempotent and safe (WS3).

Seeds a dags dir with three kinds of pre-existing file and regenerates:
  a) a stale auto-generated DAG no longer backed by any selector -> deleted
  b) a legacy single-DAG file from an older maestro -> deleted
  c) a hand-written DAG -> left completely untouched
Then regenerates twice more to confirm byte-stable output.
"""

import os
import shutil
import sys
import tempfile

import yaml

from dbt_job_maestro.config import Config
from dbt_job_maestro.airflow_dag_generator import AirflowDAGGenerator

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SCRATCH = os.environ["MAESTRO_E2E_SCRATCH"]
results = []


def check(label, condition, detail=""):
    results.append((bool(condition), label, detail))
    print(f"  [{'PASS' if condition else 'FAIL'}] {label}" + (f"  -- {detail}" if detail else ""))


cfg = Config.from_yaml(os.path.join(REPO, "e2e", "configs", "12-af-none.yml"))
selectors = yaml.safe_load(
    open(os.path.join(REPO, "e2e", "artifacts", "selectors_02-special.yml"))
)["selectors"]

workdir = tempfile.mkdtemp(prefix="maestro-idem-", dir=os.path.join(SCRATCH, "dags"))
gen = AirflowDAGGenerator(cfg.airflow)

STALE = "dbt_maestro_a_selector_that_no_longer_exists.py"
LEGACY = "dbt_maestro_dag.py"
HANDWRITTEN = "my_own_pipeline.py"
HAND_BODY = (
    '"""My hand-written DAG. Maestro must never touch this."""\n'
    "from airflow import DAG\n"
    "# no maestro marker anywhere in here\n"
    "SENTINEL = 'do-not-delete'\n"
)

with open(os.path.join(workdir, STALE), "w") as f:
    f.write("# Auto-generated by dbt-job-maestro - DO NOT EDIT\n# stale\n")
with open(os.path.join(workdir, LEGACY), "w") as f:
    f.write('"""\nAuto-generated by dbt-job-maestro.\n"""\n# legacy single-DAG layout\n')
with open(os.path.join(workdir, HANDWRITTEN), "w") as f:
    f.write(HAND_BODY)

print("\n=== first regeneration over a dirty dags dir ===")
dags = gen.generate_dags(selectors)
written, removed = gen.write_dags(dags, workdir)
check("stale auto-generated DAG was removed", STALE in removed, f"removed={len(removed)}")
check("legacy dbt_maestro_dag.py was removed", LEGACY in removed)
check("hand-written DAG was NOT removed", HANDWRITTEN not in removed)
check(
    "hand-written DAG content is byte-identical",
    open(os.path.join(workdir, HANDWRITTEN)).read() == HAND_BODY,
)
check("hand-written DAG still on disk", os.path.exists(os.path.join(workdir, HANDWRITTEN)))
check("wrote one file per generated DAG", len(written) == len(dags), f"{len(written)}/{len(dags)}")

on_disk = {f for f in os.listdir(workdir) if f.endswith(".py")}
check(
    "dags dir now holds exactly the generated set plus the hand-written file",
    on_disk == set(dags) | {HANDWRITTEN},
    f"unexpected={sorted(on_disk - set(dags) - {HANDWRITTEN})[:3]}",
)

print("\n=== repeat regeneration is byte-stable ===")
snapshot = {f: open(os.path.join(workdir, f)).read() for f in on_disk}
for run in (2, 3):
    dags2 = gen.generate_dags(selectors)
    written2, removed2 = gen.write_dags(dags2, workdir)
    after = {
        f: open(os.path.join(workdir, f)).read() for f in os.listdir(workdir) if f.endswith(".py")
    }
    check(f"run {run}: nothing removed", not removed2, f"removed={removed2[:3]}")
    check(
        f"run {run}: output byte-identical to run 1",
        after == snapshot,
        f"changed={[k for k in after if snapshot.get(k) != after[k]][:3]}",
    )

print("\n=== changing the selector set removes only the orphaned DAGs ===")
subset = [s for s in selectors if s["name"] in {"maestro_seeds", "maestro_snapshots"}]
dags3 = gen.generate_dags(subset)
written3, removed3 = gen.write_dags(dags3, workdir)
check(
    "regenerating with 2 selectors removes the rest",
    len(removed3) == len(snapshot) - len(dags3) - 1,
    f"removed={len(removed3)} was={len(snapshot)} now={len(dags3)}",
)
check(
    "hand-written DAG survived the purge",
    os.path.exists(os.path.join(workdir, HANDWRITTEN))
    and open(os.path.join(workdir, HANDWRITTEN)).read() == HAND_BODY,
)
check(
    "only the 2 generated DAGs plus hand-written remain",
    {f for f in os.listdir(workdir) if f.endswith(".py")} == set(dags3) | {HANDWRITTEN},
)

shutil.rmtree(workdir, ignore_errors=True)

failed = [r for r in results if not r[0]]
print(
    f"\n{'='*70}\nIDEMPOTENCY RESULT: {len(results)-len(failed)}/{len(results)} assertions passed"
)
if failed:
    print("FAILED:")
    for _, label, detail in failed:
        print(f"  - {label}  {detail}")
sys.exit(1 if failed else 0)
