"""Assert the Airflow DAG-generation matrix produced what each config promised.

Portable across dbt projects: expectations are relative (counts compared between
variants, structure inspected) rather than hardcoded to one project's selectors.

Reads the rendered configs to find each variant's dags_dir.

Env:
  MAESTRO_E2E_RENDERED  dir of rendered configs   [$MAESTRO_E2E_WORKDIR/configs]
  MAESTRO_E2E_WORKDIR   scratch dir
"""

import os
import re
import sys

from dbt_job_maestro.config import Config

WORKDIR = os.environ.get("MAESTRO_E2E_WORKDIR", os.environ.get("MAESTRO_E2E_SCRATCH", ""))
RENDERED = os.environ.get("MAESTRO_E2E_RENDERED", os.path.join(WORKDIR, "configs"))

results = []


def check(label, condition, detail=""):
    results.append((bool(condition), label, detail))
    print(f"  [{'PASS' if condition else 'FAIL'}] {label}" + (f"  -- {detail}" if detail else ""))


def cfg_of(name):
    path = os.path.join(RENDERED, f"{name}.yml")
    return Config.from_yaml(path) if os.path.exists(path) else None


def read_all(name):
    c = cfg_of(name)
    if not c:
        return None
    d = c.airflow.dags_dir
    if not os.path.isdir(d):
        return None
    return {f: open(os.path.join(d, f)).read() for f in sorted(os.listdir(d)) if f.endswith(".py")}


def schedules(sources):
    out = {}
    for name, src in sources.items():
        m = re.search(r"^\s+schedule(?:_interval)?=(.+),$", src, re.M)
        out[name] = m.group(1) if m else None
    return out


def commands(sources):
    return [m for v in sources.values() for m in re.findall(r'bash_command="([^"]+)"', v)]


def cron_minutes(expr):
    p = expr.strip('"').split()
    return int(p[1]) * 60 + int(p[0])


SIMPLE = read_all("10-af-simple")
if SIMPLE is None:
    print(
        f"no generated DAGs found (rendered configs: {RENDERED}) - "
        "run e2e/render_configs.sh then e2e/run_dag_matrix.sh first"
    )
    sys.exit(2)

print("\n=== 10-af-simple: one DAG per selector, runtime flags ===")
c10 = cfg_of("10-af-simple")
cmds = commands(SIMPLE)
check("produced DAG files", len(SIMPLE) > 0, f"{len(SIMPLE)} files")
check(
    "every file carries the generated marker",
    all("# Auto-generated by dbt-job-maestro" in v for v in SIMPLE.values()),
)
check(
    "every DAG has exactly one dag_id",
    all(len(re.findall(r'dag_id="', v)) == 1 for v in SIMPLE.values()),
)
check("every command passes --project-dir", all("--project-dir " in c for c in cmds))
check("every command passes --profiles-dir", all("--profiles-dir " in c for c in cmds))
check(
    f"every command passes --target {c10.airflow.dbt_target}",
    all(f"--target {c10.airflow.dbt_target}" in c for c in cmds),
)
check(
    f"every command passes --threads {c10.airflow.dbt_threads}",
    all(f"--threads {c10.airflow.dbt_threads}" in c for c in cmds),
)
check(
    "all schedules are the configured cron",
    set(schedules(SIMPLE).values()) == {f'"{c10.airflow.schedule_interval}"'},
    str(set(schedules(SIMPLE).values()))[:70],
)
check("seeds selector uses `dbt seed`", any(c.startswith("dbt seed ") for c in cmds))
check("snapshots selector uses `dbt snapshot`", any(c.startswith("dbt snapshot ") for c in cmds))
check("model selectors use `dbt build`", any(c.startswith("dbt build ") for c in cmds))
check("v2 emits schedule_interval kwarg", all("schedule_interval=" in v for v in SIMPLE.values()))
check(
    "v2 uses the legacy BashOperator import",
    all("from airflow.operators.bash import BashOperator" in v for v in SIMPLE.values()),
)
check("all files are valid Python", all(compile(v, k, "exec") or True for k, v in SIMPLE.items()))

STAG = read_all("11-af-staggered")
if STAG:
    print("\n=== 11-af-staggered: offsets, day-of-week, SLA, execution_order ===")
    c11 = cfg_of("11-af-staggered")
    sch = schedules(STAG)
    manual_cron = f'"{c11.airflow.manual_schedule_interval}"'
    auto_crons = sorted({v for v in sch.values() if v and v != manual_cron})
    inc, start = (
        c11.airflow.cron_increment_minutes,
        c11.airflow.start_hour * 60 + c11.airflow.start_minute,
    )
    check(
        "staggered crons are not all identical", len(auto_crons) > 1, f"{len(auto_crons)} distinct"
    )
    if c11.airflow.cron_days_of_week:
        day_map = {
            "SUN": "0",
            "MON": "1",
            "TUE": "2",
            "WED": "3",
            "THU": "4",
            "FRI": "5",
            "SAT": "6",
        }
        want = ",".join(day_map[d.upper()] for d in c11.airflow.cron_days_of_week)
        check(
            f"crons carry the configured days of week ({want})",
            all(c.strip('"').endswith(want) for c in auto_crons),
            auto_crons[:2],
        )
    mins = sorted(cron_minutes(c) for c in auto_crons)
    check(
        f"every staggered cron sits on the {inc}-minute grid from the start time",
        all((m - start) % inc == 0 for m in mins),
        f"offenders={[m for m in mins if (m - start) % inc][:3]}",
    )
    check("no two auto DAGs share a staggered slot", len(mins) == len(set(mins)))
    if c11.airflow.manual_schedule_interval:
        check("manual selectors use manual_schedule_interval", manual_cron in sch.values())
        mf = [k for k, v in sch.items() if v == manual_cron]
        if c11.airflow.manual_sla_minutes > 0:
            check(
                f"manual DAGs get manual_sla_minutes={c11.airflow.manual_sla_minutes}",
                all(
                    f'"sla": timedelta(minutes={c11.airflow.manual_sla_minutes})' in STAG[k]
                    for k in mf
                ),
                f"{len(mf)} manual DAGs",
            )
        af = [k for k, v in sch.items() if v != manual_cron]
        if c11.airflow.sla_minutes > 0:
            check(
                f"auto DAGs get sla_minutes={c11.airflow.sla_minutes}",
                all(f'"sla": timedelta(minutes={c11.airflow.sla_minutes})' in STAG[k] for k in af),
            )
    if c11.airflow.execution_order[:1] == ["seeds"]:
        seed_dags = [k for k in STAG if k.endswith("_seeds.py")]
        model_dags = [
            k
            for k, v in sch.items()
            if v != manual_cron and k not in seed_dags and not k.endswith("_snapshots.py")
        ]
        if seed_dags and model_dags:
            check(
                "execution_order schedules seeds before models",
                max(cron_minutes(sch[k]) for k in seed_dags)
                < max(cron_minutes(sch[k]) for k in model_dags),
            )

NONE = read_all("12-af-none")
if NONE:
    print("\n=== 12-af-none: no schedule ===")
    check("every DAG has schedule_interval=None", set(schedules(NONE).values()) == {"None"})
    check("no SLA emitted when sla_minutes=0", not any('"sla"' in v for v in NONE.values()))

FF, CO = read_all("13-af-combined-failfast"), read_all("14-af-combined-continue")
if FF and CO:
    print("\n=== 13/14: combined small selectors, fail-fast vs continue ===")
    cname = next((f for f in FF if f.endswith("combined_small_selectors.py")), None)
    check("13 produced a combined DAG", cname is not None)
    check("14 produced a combined DAG", any(f.endswith("combined_small_selectors.py") for f in CO))
    check(
        "combining reduced the DAG count vs one-per-selector",
        len(FF) < len(SIMPLE),
        f"{len(FF)} vs {len(SIMPLE)}",
    )
    if cname:
        d13, d14 = (
            re.findall(r"^\s+(\w+) >> (\w+)$", FF[cname], re.M),
            re.findall(r"^\s+(\w+) >> (\w+)$", CO[cname], re.M),
        )
        t13, t14 = (
            re.findall(r'task_id="([^"]+)"', FF[cname]),
            re.findall(r'task_id="([^"]+)"', CO[cname]),
        )
        check("fail-fast chains task groups with >>", len(d13) > 0, f"{len(d13)} chain links")
        check(
            "continue_on_failure leaves groups independent (no >>)",
            len(d14) == 0,
            f"{len(d14)} chain links",
        )
        check("both combined DAGs contain the same tasks", t13 == t14, f"{len(t13)} vs {len(t14)}")
    check(
        "seeds/snapshots are never combined",
        any(f.endswith("_seeds.py") for f in FF) and any(f.endswith("_snapshots.py") for f in FF),
    )

CMD = read_all("15-af-commands")
if CMD:
    print("\n=== 15-af-commands: run_test + per-selector overrides ===")
    c15 = cfg_of("15-af-commands")
    prefix = c15.airflow.selector_prefix + "_"
    auto_files = {
        k: v
        for k, v in CMD.items()
        if not k.endswith(("_seeds.py", "_snapshots.py"))
        and re.search(r'dag_id="[^"]*' + re.escape(prefix), v)
    }
    check(
        "default_command=run_test emits two tasks on auto selectors",
        any(len(re.findall(r'task_id="', v)) == 2 for v in auto_files.values()),
    )
    check(
        "run_test wires run >> test",
        any(re.search(r"run_\w+ >> test_\w+", v) for v in auto_files.values()),
    )
    check(
        "auto selectors use `dbt run` (the run half of run_test)",
        any("dbt run --selector" in v for v in auto_files.values()),
    )
    check(
        "auto selectors IGNORE selector_commands overrides",
        all("dbt build --selector" not in v for v in auto_files.values()),
        "auto must use default_command uniformly",
    )
    seeds = next((v for k, v in CMD.items() if k.endswith("_seeds.py")), "")
    snaps = next((v for k, v in CMD.items() if k.endswith("_snapshots.py")), "")
    check(
        "seeds keep `dbt seed` despite default_command=run_test",
        "dbt seed --selector" in seeds and "dbt run " not in seeds,
    )
    check(
        "snapshots keep `dbt snapshot` despite default_command=run_test",
        "dbt snapshot --selector" in snaps,
    )

FR = read_all("16-af-fullrefresh")
if FR:
    print("\n=== 16-af-fullrefresh: auto + custom shapes + seeds ===")
    c16 = cfg_of("16-af-fullrefresh")
    pre = c16.airflow.dag_id_prefix
    sch = schedules(FR)
    check(
        "extra full-refresh DAGs beyond the per-selector set",
        len(FR) > len(SIMPLE),
        f"{len(FR)} vs {len(SIMPLE)}",
    )
    if c16.airflow.full_refresh.enabled:
        f = f"{pre}_full_refresh_incremental.py"
        check(f"{f} exists", f in FR)
        if f in FR:
            check(
                "auto full-refresh uses build --full-refresh --selector",
                "dbt build --full-refresh --selector" in FR[f],
            )
            check(
                "auto full-refresh has its own cron",
                sch.get(f) == f'"{c16.airflow.full_refresh.cron_schedule}"',
            )
    shape_expect = {
        "selector": "--full-refresh --selector",
        "tags": "--full-refresh --select tag:",
        "paths": "--full-refresh --select path:",
        "models": "--full-refresh --select ",
    }
    for sched in c16.airflow.full_refresh.custom_schedules:
        f = f"{pre}_full_refresh_{sched.name}.py"
        check(f"{f} exists", f in FR)
        if f in FR:
            kind = (
                "selector"
                if sched.selector
                else "tags" if sched.tags else "paths" if sched.paths else "models"
            )
            check(f"{f}: command matches its {kind} shape", shape_expect[kind] in FR[f])
            check(f"{f}: own cron {sched.cron_schedule}", sch.get(f) == f'"{sched.cron_schedule}"')
    if c16.airflow.seeds_full_refresh.enabled:
        f = f"{pre}_seeds_full_refresh.py"
        check(f"{f} exists", f in FR)
        if f in FR:
            check(
                "seeds full-refresh uses seed --full-refresh",
                "dbt seed --full-refresh --selector" in FR[f],
            )

LEG = read_all("17-af-legacy")
if LEG:
    print("\n=== 17-af-legacy: back-compat normalization ===")
    c17 = cfg_of("17-af-legacy")
    check(
        "legacy orchestration_mode normalized to 'simple'",
        c17.airflow.orchestration_mode == "simple",
        c17.airflow.orchestration_mode,
    )
    check(
        "legacy mode still produces scheduled DAGs",
        set(schedules(LEG).values()) == {f'"{c17.airflow.schedule_interval}"'},
    )

V3 = read_all("18-af-v3")
if V3:
    print("\n=== 18-af-v3: Airflow 3 targeting ===")
    c18 = cfg_of("18-af-v3")
    check("config requests airflow_version 3", c18.airflow.airflow_version == 3)
    check(
        "v3 uses schedule= not schedule_interval=",
        all("schedule_interval=" not in v for v in V3.values())
        and all(re.search(r"^\s+schedule=", v, re.M) for v in V3.values()),
    )
    check(
        "v3 uses the provider BashOperator import",
        all(
            "from airflow.providers.standard.operators.bash import BashOperator" in v
            for v in V3.values()
        ),
    )
    check(
        "v3 omits sla (removed in Airflow 3.0)",
        not any('"sla"' in v for v in V3.values()),
        f"sla_minutes={c18.airflow.sla_minutes}",
    )

print("\n=== selector names that are not valid Python identifiers ===")
odd = {
    k: v
    for k, v in SIMPLE.items()
    if not re.sub(r"\.py$", "", k).replace("-", "_").replace(".", "_").isidentifier()
    or "-" in k
    or "." in k[:-3]
}
if odd:
    for k, v in list(odd.items())[:5]:
        assigns = re.findall(r"^\s+(\S+) = BashOperator\($", v, re.M)
        check(
            f"{k}: python variable names are valid identifiers",
            all(a.isidentifier() for a in assigns),
            str(assigns[:2]),
        )
else:
    print("  (none in this project - nothing to check)")

failed = [r for r in results if not r[0]]
print(f"\n{'='*70}\nRESULT: {len(results)-len(failed)}/{len(results)} assertions passed")
if failed:
    print("FAILED:")
    for _, label, detail in failed:
        print(f"  - {label}  {detail}")
sys.exit(1 if failed else 0)
