"""Generate Airflow DAG Python files from dbt selectors.

Mirrors the dbt Cloud job generator: maestro emits ONE DAG file per selector
(the Airflow analogue of one job per selector). Each DAG gets its own schedule,
SLA and retry policy. Generation is idempotent - every auto-generated file
carries a marker comment and is rebuilt on each run; stale auto-generated files
are removed, while hand-written DAGs are left untouched.
"""

import logging
import os
import re
import shlex
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

import yaml

from dbt_job_maestro.config import AirflowConfig, CustomFullRefreshSchedule
from dbt_job_maestro.dbt_commands import build_steps, resolve_command
from dbt_job_maestro.selector_types import count_fqn_models

# Marker written into every generated file. Used to recognise (and safely
# overwrite / clean up) maestro-owned DAGs without touching hand-written ones.
GENERATED_MARKER = "# Auto-generated by dbt-job-maestro - DO NOT EDIT"

# Looser phrase present in BOTH the current marker and the docstring of files
# produced by older maestro versions. Cleanup detects this so regenerating also
# removes legacy single-DAG files (e.g. an old dbt_maestro_dag.py).
GENERATED_PHRASE = "Auto-generated by dbt-job-maestro"

logger = logging.getLogger(__name__)


class AirflowDAGGenerator:
    """Generate one Airflow DAG file per selector from selectors.yml."""

    def __init__(
        self,
        config: AirflowConfig,
        manifest_data: Optional[Dict[str, Any]] = None,
    ):
        # manifest_data is not used to wire task dependencies - one-DAG-per-selector
        # cannot express cross-selector order. It is used for `lineage_tasks`, which
        # renders the *intra*-selector dbt graph as visual-only nodes.
        self.config = config
        self.manifest_data = manifest_data
        self._model_index = self._build_model_index(manifest_data)
        self._resolver = self._build_resolver(manifest_data)

    # ------------------------------------------------------------------
    # Lineage (visual only)
    # ------------------------------------------------------------------

    @staticmethod
    def _build_model_index(manifest_data: Optional[Dict[str, Any]]) -> Dict[str, Dict[str, Any]]:
        """Index manifest models by name: materialization, relation, parent names."""
        if not manifest_data:
            return {}
        nodes = manifest_data.get("nodes", {})
        uid_to_name = {
            uid: n.get("name") for uid, n in nodes.items() if n.get("resource_type") == "model"
        }
        index: Dict[str, Dict[str, Any]] = {}
        for node in nodes.values():
            if node.get("resource_type") != "model":
                continue
            name = node.get("name")
            if not name:
                continue
            parents = [
                uid_to_name[dep]
                for dep in node.get("depends_on", {}).get("nodes", [])
                if dep in uid_to_name
            ]
            index[name] = {
                "materialized": node.get("config", {}).get("materialized", "view"),
                "relation": ".".join(
                    str(p) for p in (node.get("database"), node.get("schema"), name) if p
                ),
                "parents": parents,
            }
        return index

    @staticmethod
    def _build_resolver(manifest_data: Optional[Dict[str, Any]]):
        """Build a ModelResolver over the manifest, or None when unavailable."""
        if not manifest_data:
            return None
        try:
            from dbt_job_maestro.graph_builder import GraphBuilder
            from dbt_job_maestro.manifest_parser import ManifestParser
            from dbt_job_maestro.model_resolver import ModelResolver

            # Bypass __init__: it reads manifest.json from disk, and the caller
            # already has the parsed manifest in memory.
            parser = ManifestParser.__new__(ManifestParser)
            parser.manifest_path = None
            parser.manifest_data = manifest_data
            models = parser.get_models()
            return ModelResolver(parser, GraphBuilder(models))
        except Exception as exc:  # pragma: no cover - defensive
            logger.debug("Lineage disabled, could not build resolver: %s", exc)
            return None

    def _lineage_for(
        self, selector: Dict[str, Any]
    ) -> Optional[Tuple[List[str], List[Tuple[str, str]]]]:
        """Resolve a selector to (sorted model names, parent->child edges).

        Returns None when lineage is off, the manifest is missing, the selector
        resolves to nothing, or it exceeds ``lineage_max_models``.
        """
        if not self.config.lineage_tasks or self._resolver is None:
            return None
        try:
            models = self._resolver.resolve_selector(selector).models
        except Exception as exc:  # pragma: no cover - defensive
            logger.debug("Lineage skipped for %s: %s", selector.get("name"), exc)
            return None

        models = {m for m in models if m in self._model_index}
        if not models:
            return None
        cap = self.config.lineage_max_models
        if cap and len(models) > cap:
            logger.debug(
                "Lineage skipped for %s: %d models exceeds lineage_max_models=%d",
                selector.get("name"),
                len(models),
                cap,
            )
            return None

        edges = [
            (parent, model)
            for model in sorted(models)
            for parent in sorted(self._model_index[model]["parents"])
            if parent in models
        ]
        return sorted(models), edges

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def generate_dags(self, selectors: List[Dict[str, Any]]) -> Dict[str, str]:
        """Generate DAG files from selectors.

        Args:
            selectors: Selector definitions loaded from selectors.yml.

        Returns:
            Mapping of ``filename -> python_source`` for each generated DAG.
        """
        self.config.validate()
        prefix = f"{self.config.selector_prefix}_"
        full_refresh_selector_name = f"{self.config.selector_prefix}_full_refresh_incremental"

        # Drop freshness selectors and the full-refresh selector (handled below).
        candidates = [
            s
            for s in selectors
            if not s["name"].startswith("freshness_")
            and not s["name"].startswith("automatically_generated_freshness_")
            and s["name"] != full_refresh_selector_name
        ]

        # Apply maestro/manual inclusion settings.
        filtered: List[Dict[str, Any]] = []
        for sel in candidates:
            is_auto = sel["name"].startswith(prefix)
            if is_auto and not self.config.include_maestro_selectors_in_dags:
                continue
            if not is_auto and not self.config.include_manual_selectors_in_dags:
                continue
            filtered.append(sel)

        if self.config.execution_order:
            filtered = self._sort_by_execution_order(filtered)

        # Partition into "large" (own DAG) and "small" (combined) selectors.
        large, small = self._partition_by_size(filtered, prefix)

        dags: Dict[str, str] = {}
        dag_index = 0

        for sel in large:
            name = sel["name"]
            is_manual = not name.startswith(prefix)
            dag_id = self._dag_id_for(name)
            schedule = self._schedule_for(is_manual, dag_index)
            sla = self._sla_for(is_manual)
            # One task group for this selector (2 tasks when its command is run_test).
            task_groups = [self._task_group_for(sel)]
            kind = "manual" if is_manual else "auto"
            dags[f"{dag_id}.py"] = self._render_dag(
                dag_id,
                schedule,
                sla,
                task_groups,
                extra_tags=[kind],
                lineage=self._lineage_for(sel),
                lineage_selector=name,
            )
            dag_index += 1

        if small:
            dag_id = f"{self.config.dag_id_prefix}_combined_small_selectors"
            schedule = self._schedule_for(False, dag_index)
            sla = self._sla_for(False)
            # One task group per selector. Groups are chained sequentially unless
            # continue_on_failure is set, in which case they stay independent so a
            # failing selector does not skip its siblings.
            task_groups = [self._task_group_for(s) for s in small]
            dags[f"{dag_id}.py"] = self._render_dag(
                dag_id, schedule, sla, task_groups, chain=True, extra_tags=["auto", "combined"]
            )
            dag_index += 1

        # Full-refresh DAGs (each its own file with its own cron).
        dags.update(self._generate_full_refresh_dags())

        return dags

    def write_dags(self, dags: Dict[str, str], dags_dir: str) -> Tuple[List[str], List[str]]:
        """Write generated DAGs to a directory, idempotently.

        Writes/overwrites every file in ``dags``, then deletes any *other*
        ``.py`` file in the directory that carries the generated marker (a stale
        auto-generated DAG no longer backed by a selector). Files without the
        marker (hand-written DAGs) are never touched.

        Args:
            dags: Mapping of filename -> python source.
            dags_dir: Destination directory.

        Returns:
            Tuple of (written filenames, removed filenames).
        """
        os.makedirs(dags_dir or ".", exist_ok=True)

        written = sorted(dags.keys())
        for filename, source in dags.items():
            with open(os.path.join(dags_dir, filename), "w") as f:
                f.write(source)

        removed: List[str] = []
        for existing in os.listdir(dags_dir):
            if not existing.endswith(".py") or existing in dags:
                continue
            path = os.path.join(dags_dir, existing)
            if not os.path.isfile(path):
                continue
            if self._is_generated_file(path):
                os.remove(path)
                removed.append(existing)

        return written, sorted(removed)

    # ------------------------------------------------------------------
    # Selector classification & dbt command helpers
    # ------------------------------------------------------------------

    def _get_selector_type(self, selector_name: str) -> str:
        """Classify a selector as 'seeds', 'snapshots', 'full_refresh', or 'models'."""
        prefix = self.config.selector_prefix
        if selector_name == f"{prefix}_seeds" or selector_name.endswith("_seeds"):
            return "seeds"
        if selector_name == f"{prefix}_snapshots" or selector_name.endswith("_snapshots"):
            return "snapshots"
        if selector_name.endswith("_full_refresh_incremental"):
            return "full_refresh"
        return "models"

    def _task_group_for(self, selector: Dict[str, Any]) -> List[Tuple[str, str]]:
        """Build the ordered task(s) for a selector.

        Returns a list of ``(task_id, bash_command)`` tuples. Most selectors map
        to a single task; a model selector whose command is ``run_test`` maps to
        two tasks (run, then test) that the renderer chains ``run >> test``.
        Seeds, snapshots and full-refresh selectors keep their type-specific
        command and ignore the configurable per-selector command. Per-selector
        command overrides apply to manual selectors only; auto-generated
        selectors all use ``default_command``.
        """
        name = selector["name"]
        sel_type = self._get_selector_type(name)
        flags = self._dbt_runtime_flags()

        if sel_type == "seeds":
            cmd = " ".join(["dbt", "seed", "--selector", name] + flags)
            return [(self._task_id(name), cmd)]
        if sel_type == "snapshots":
            cmd = " ".join(["dbt", "snapshot", "--selector", name] + flags)
            return [(self._task_id(name), cmd)]
        if sel_type == "full_refresh":
            cmd = " ".join(["dbt", "build", "--full-refresh", "--selector", name] + flags)
            return [(self._task_id(name), cmd)]

        # Model selectors: honour the configurable command.
        command = resolve_command(
            name,
            self.config.default_command,
            self.config.selector_commands,
            self.config.selector_prefix,
        )
        steps = build_steps(command, name, " ".join(flags))
        if command == "run_test":
            return [(f"run_{name}", steps[0]), (f"test_{name}", steps[1])]
        return [(self._task_id(name), steps[0])]

    def _get_dbt_command(self, selector: Dict[str, Any]) -> str:
        """Primary dbt command string for a selector (first task's command)."""
        return self._task_group_for(selector)[0][1]

    def _dbt_runtime_flags(self) -> List[str]:
        """Common --project-dir/--profiles-dir/--target/--threads flags."""
        flags: List[str] = []
        if self.config.dbt_project_dir:
            flags += ["--project-dir", shlex.quote(self.config.dbt_project_dir)]
        if self.config.dbt_profiles_dir:
            flags += ["--profiles-dir", shlex.quote(self.config.dbt_profiles_dir)]
        if self.config.dbt_target:
            flags += ["--target", self.config.dbt_target]
        if self.config.dbt_threads:
            flags += ["--threads", str(self.config.dbt_threads)]
        return flags

    def _dbt_deps_task(self) -> Tuple[str, str]:
        """``(task_id, bash_command)`` for the "dbt deps" task.

        Only --project-dir/--profiles-dir are relevant to "dbt deps"; --target
        and --threads are dropped since they don't affect package installation.
        """
        flags: List[str] = []
        if self.config.dbt_project_dir:
            flags += ["--project-dir", shlex.quote(self.config.dbt_project_dir)]
        if self.config.dbt_profiles_dir:
            flags += ["--profiles-dir", shlex.quote(self.config.dbt_profiles_dir)]
        cmd = " ".join(["dbt", "deps"] + flags)
        return ("dbt_deps", cmd)

    # ------------------------------------------------------------------
    # Partitioning, ordering, naming
    # ------------------------------------------------------------------

    def _partition_by_size(
        self, selectors: List[Dict[str, Any]], prefix: str
    ) -> Tuple[List[Dict[str, Any]], List[Dict[str, Any]]]:
        """Split selectors into (large=own DAG, small=combined).

        Only auto-generated (maestro) selectors with a positive model count
        below min_models_per_dag are "small". Manual selectors and non-model
        resources always get their own DAG.
        """
        if self.config.min_models_per_dag <= 1:
            return selectors, []

        large: List[Dict[str, Any]] = []
        small: List[Dict[str, Any]] = []
        for sel in selectors:
            is_auto = sel["name"].startswith(prefix)
            if not is_auto or self._get_selector_type(sel["name"]) != "models":
                large.append(sel)
                continue
            count = count_fqn_models(sel)
            if 0 < count < self.config.min_models_per_dag:
                small.append(sel)
            else:
                large.append(sel)
        return large, small

    def _sort_by_execution_order(self, selectors: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
        """Order selectors by configured resource-type execution_order."""
        order = {rt: i for i, rt in enumerate(self.config.execution_order)}
        default = len(self.config.execution_order)

        def key(sel: Dict[str, Any]) -> Tuple[int, str]:
            rt = self._get_selector_type(sel["name"])
            # full_refresh isn't an execution_order value; treat it like models.
            lookup = "models" if rt == "full_refresh" else rt
            return (order.get(lookup, default), sel["name"])

        return sorted(selectors, key=key)

    def _dag_id_for(self, selector_name: str) -> str:
        """Build a DAG id from a selector name."""
        return f"{self.config.dag_id_prefix}_{selector_name}"

    def _task_id(self, selector_name: str) -> str:
        """Airflow task_id for a selector's task (hyphens/dots are valid here)."""
        return f"run_{selector_name}"

    @staticmethod
    def _safe_var(task_id: str) -> str:
        """Turn a task_id into a valid Python variable name.

        Selector names may contain characters that are legal in Airflow
        task_ids/dag_ids (e.g. '-', '.') but not in Python identifiers, which
        would otherwise produce a SyntaxError in the generated assignment.
        """
        var = re.sub(r"\W", "_", task_id)
        if var and var[0].isdigit():
            var = f"_{var}"
        return var

    # ------------------------------------------------------------------
    # Schedule & SLA resolution
    # ------------------------------------------------------------------

    def _schedule_for(self, is_manual: bool, dag_index: int) -> Optional[str]:
        """Resolve the cron schedule for a DAG (None = no schedule)."""
        if self.config.orchestration_mode == "none":
            return None
        if is_manual and self.config.manual_schedule_interval:
            return self.config.manual_schedule_interval
        if self.config.orchestration_mode == "staggered":
            return self._staggered_cron(dag_index)
        return self.config.schedule_interval

    def _sla_for(self, is_manual: bool) -> int:
        """Resolve the SLA in minutes for a DAG (0 = no SLA)."""
        if is_manual and self.config.manual_sla_minutes >= 0:
            return self.config.manual_sla_minutes
        return self.config.sla_minutes

    def _staggered_cron(self, dag_index: int) -> str:
        """Cron offset by cron_increment_minutes per DAG from the start time."""
        total = (
            self.config.start_hour * 60
            + self.config.start_minute
            + dag_index * self.config.cron_increment_minutes
        )
        hour = (total // 60) % 24
        minute = total % 60

        if self.config.cron_days_of_week:
            day_map = {
                "SUN": "0",
                "MON": "1",
                "TUE": "2",
                "WED": "3",
                "THU": "4",
                "FRI": "5",
                "SAT": "6",
            }
            days = ",".join(day_map.get(d.upper(), "*") for d in self.config.cron_days_of_week)
        else:
            days = "*"

        return f"{minute} {hour} * * {days}"

    # ------------------------------------------------------------------
    # Full refresh DAGs
    # ------------------------------------------------------------------

    def _generate_full_refresh_dags(self) -> Dict[str, str]:
        """Build the full-refresh / seeds-full-refresh DAGs."""
        dags: Dict[str, str] = {}
        fr = self.config.full_refresh

        if fr.enabled:
            dag_id = f"{self.config.dag_id_prefix}_full_refresh_incremental"
            selector = f"{self.config.selector_prefix}_full_refresh_incremental"
            cmd = " ".join(
                ["dbt", "build", "--full-refresh", "--selector", selector]
                + self._dbt_runtime_flags()
            )
            tasks = [(self._task_id(selector), cmd)]
            dags[f"{dag_id}.py"] = self._render_dag(
                dag_id,
                None if self.config.orchestration_mode == "none" else fr.cron_schedule,
                0,
                [tasks],
                extra_tags=["auto", "full-refresh"],
            )

        for schedule in fr.custom_schedules:
            if not schedule.name:
                continue
            cmd = self._custom_full_refresh_command(schedule)
            if not cmd:
                continue
            dag_id = f"{self.config.dag_id_prefix}_full_refresh_{schedule.name}"
            tasks = [(f"run_full_refresh_{schedule.name}", cmd)]
            dags[f"{dag_id}.py"] = self._render_dag(
                dag_id,
                None if self.config.orchestration_mode == "none" else schedule.cron_schedule,
                0,
                [tasks],
                extra_tags=["auto", "full-refresh"],
            )

        if self.config.seeds_full_refresh.enabled:
            dag_id = f"{self.config.dag_id_prefix}_seeds_full_refresh"
            selector = f"{self.config.selector_prefix}_seeds"
            cmd = " ".join(
                ["dbt", "seed", "--full-refresh", "--selector", selector]
                + self._dbt_runtime_flags()
            )
            tasks = [(self._task_id(selector), cmd)]
            dags[f"{dag_id}.py"] = self._render_dag(
                dag_id,
                (
                    None
                    if self.config.orchestration_mode == "none"
                    else self.config.seeds_full_refresh.cron_schedule
                ),
                0,
                [tasks],
                extra_tags=["auto", "full-refresh"],
            )

        return dags

    def _custom_full_refresh_command(self, schedule: CustomFullRefreshSchedule) -> Optional[str]:
        """Build the dbt command for a custom full-refresh schedule."""
        if schedule.selector:
            parts = ["dbt", "build", "--full-refresh", "--selector", schedule.selector]
        elif schedule.tags:
            selects = " ".join(f"tag:{t}" for t in schedule.tags)
            parts = ["dbt", "build", "--full-refresh", "--select", selects]
        elif schedule.paths:
            selects = " ".join(f"path:{p}" for p in schedule.paths)
            parts = ["dbt", "build", "--full-refresh", "--select", selects]
        elif schedule.models:
            selects = " ".join(schedule.models)
            parts = ["dbt", "build", "--full-refresh", "--select", selects]
        else:
            return None
        return " ".join(parts + self._dbt_runtime_flags())

    # ------------------------------------------------------------------
    # Rendering
    # ------------------------------------------------------------------

    def _render_dag(
        self,
        dag_id: str,
        schedule_interval: Optional[str],
        sla_minutes: int,
        task_groups: List[List[Tuple[str, str]]],
        chain: bool = False,
        extra_tags: Optional[List[str]] = None,
        lineage: Optional[Tuple[List[str], List[Tuple[str, str]]]] = None,
        lineage_selector: str = "",
    ) -> str:
        """Render a single DAG file.

        Args:
            dag_id: Airflow DAG id.
            schedule_interval: Cron string, or None for manual-trigger DAGs.
            sla_minutes: Task SLA in minutes (0 = no SLA).
            task_groups: List of task groups. Each group is a list of
                ``(task_id, bash_command)`` tuples that always run in order
                within the group (e.g. ``run >> test`` for a run_test selector).
            chain: If True, wire the groups to each other sequentially (used for
                the combined DAG). When ``config.continue_on_failure`` is True the
                groups are left independent instead, so a failing selector does
                not skip its siblings. Tasks within a group are always chained.
            extra_tags: DAG-kind tags appended to the configured ``tags`` (e.g.
                "manual" vs "auto", "combined", "full-refresh") so manual and
                auto-generated DAGs can be told apart in the Airflow UI.
            lineage: Optional ``(models, edges)`` from :meth:`_lineage_for`. When
                given, a visual-only ``lineage`` TaskGroup of EmptyOperators is
                emitted downstream of the dbt task.
            lineage_selector: Selector name, used in the lineage docstring.
        """
        # Airflow 3 moved BashOperator and EmptyOperator into the standard provider.
        if self.config.airflow_version >= 3:
            bash_import = "from airflow.providers.standard.operators.bash import BashOperator"
            empty_import = "from airflow.providers.standard.operators.empty import EmptyOperator"
        else:
            bash_import = "from airflow.operators.bash import BashOperator"
            empty_import = "from airflow.operators.empty import EmptyOperator"

        lines: List[str] = [
            '"""',
            "Auto-generated by dbt-job-maestro.",
            "DO NOT EDIT - regenerate with: maestro generate-dags",
            '"""',
            GENERATED_MARKER,
            "",
            "from datetime import datetime, timedelta",
            "",
            "from airflow import DAG",
        ]
        if self.config.operator == "dbt":
            if self.config.run_dbt_deps:
                lines.append(bash_import)
            lines += [
                "from pathlib import Path",
                "from cosmos import (",
                "    DbtBuildLocalOperator,",
                "    DbtRunLocalOperator,",
                "    DbtSeedLocalOperator,",
                "    DbtSnapshotLocalOperator,",
                "    DbtTestLocalOperator,",
                "    ProfileConfig,",
                ")",
            ]
        else:
            lines.append(bash_import)
        if lineage:
            lines += [empty_import, "from airflow.utils.task_group import TaskGroup"]
        lines += ["", ""]

        if self.config.operator == "dbt":
            lines += [
                "profile_config = ProfileConfig(",
                f"    profile_name={self._python_literal(self._resolve_dbt_profile())},",
                f"    target_name={self._python_literal(self.config.dbt_target)},",
                f"    profiles_yml_filepath={self._profiles_yml_path_expression()},",
                ")",
                "",
            ]

        if lineage:
            lines += self._lineage_doc_lines(lineage, lineage_selector) + ["", ""]

        # default_args
        lines += [
            "default_args = {",
            f'    "owner": "{self.config.owner}",',
            '    "depends_on_past": False,',
            '    "email_on_failure": False,',
            f'    "retries": {self.config.retries},',
            f'    "retry_delay": timedelta(minutes={self.config.retry_delay_minutes}),',
        ]
        # Task SLAs were removed in Airflow 3.0, so "sla" must not be emitted there.
        if sla_minutes > 0 and self.config.airflow_version < 3:
            lines.append(f'    "sla": timedelta(minutes={sla_minutes}),')
        lines += ["}", "", ""]

        # DAG context
        try:
            dt = datetime.strptime(self.config.start_date, "%Y-%m-%d")
            start_date_expr = f"datetime({dt.year}, {dt.month}, {dt.day})"
        except ValueError:
            start_date_expr = "datetime(2024, 1, 1)"

        schedule_expr = f'"{schedule_interval}"' if schedule_interval is not None else "None"

        # Append DAG-kind tags (manual/auto/combined/full-refresh) to the
        # configured base tags, de-duplicated and order-preserving.
        dag_tags = list(self.config.tags)
        for tag in extra_tags or []:
            if tag not in dag_tags:
                dag_tags.append(tag)

        # Airflow 3 removed the schedule_interval kwarg in favour of schedule.
        schedule_kwarg = "schedule" if self.config.airflow_version >= 3 else "schedule_interval"

        lines += [
            "with DAG(",
            f'    dag_id="{dag_id}",',
            "    default_args=default_args,",
            f"    {schedule_kwarg}={schedule_expr},",
            f"    start_date={start_date_expr},",
            "    catchup=False,",
            f"    tags={repr(dag_tags)},",
        ]
        if lineage:
            lines.append("    doc_md=LINEAGE_DOC,")
        lines += [
            ") as dag:",
            "",
        ]

        # "dbt deps" task, rendered first so dbt_packages/ is always installed
        # and up to date before any build/run/test/seed/snapshot task runs.
        deps_task: Optional[Tuple[str, str]] = (
            self._dbt_deps_task() if self.config.run_dbt_deps else None
        )
        if deps_task:
            deps_task_id, deps_cmd = deps_task
            deps_var = self._safe_var(deps_task_id)
            lines += [
                f"    {deps_var} = BashOperator(",
                f'        task_id="{deps_task_id}",',
                f'        bash_command="{deps_cmd}",',
            ]
            # Cosmos deprecated its deps operator. Keep this one setup step as
            # BashOperator while selector execution uses Cosmos's supported local operators.
            if self.config.dbt_deps_pool:
                lines.append(f'        pool="{self.config.dbt_deps_pool}",')
            lines += ["    )", ""]

        # Tasks. task_id keeps the (possibly hyphenated) selector name; the
        # Python variable is sanitised so the assignment is always valid.
        for group in task_groups:
            for task_id, cmd in group:
                if self.config.operator == "dbt":
                    lines += self._cosmos_task_lines(task_id, cmd)
                else:
                    task_var = self._safe_var(task_id)
                    lines += [
                        f"    {task_var} = BashOperator(",
                        f'        task_id="{task_id}",',
                        f'        bash_command="{cmd}",',
                        "    )",
                        "",
                    ]

        # Dependencies:
        #  - "dbt deps" always gates every group's first task, so packages are
        #    installed/refreshed before any selector work runs;
        #  - within a group, tasks always run in order (e.g. run >> test);
        #  - across groups, chain sequentially (mirrors a job's ordered
        #    execute_steps) UNLESS continue_on_failure is set, in which case the
        #    groups stay independent so a failing selector never skips its siblings.
        dependency_lines: List[str] = []
        if deps_task:
            deps_var = self._safe_var(deps_task[0])
            for group in task_groups:
                dependency_lines.append(f"{deps_var} >> {self._safe_var(group[0][0])}")
        for group in task_groups:
            if len(group) > 1:
                dependency_lines.append(
                    " >> ".join(self._safe_var(task_id) for task_id, _ in group)
                )
        if chain and not self.config.continue_on_failure and len(task_groups) > 1:
            for prev, nxt in zip(task_groups, task_groups[1:]):
                dependency_lines.append(
                    f"{self._safe_var(prev[-1][0])} >> {self._safe_var(nxt[0][0])}"
                )

        if dependency_lines:
            lines.append("    # Task dependencies")
            for dep in dependency_lines:
                lines.append(f"    {dep}")
            lines.append("")

        if lineage:
            lines += self._lineage_task_lines(lineage, task_groups)

        return "\n".join(lines) + "\n"

    def _resolve_dbt_profile(self) -> str:
        """Resolve Cosmos's required profile name from config or dbt_project.yml."""
        if self.config.dbt_profile:
            return self.config.dbt_profile

        project_dir = Path(self.config.dbt_project_dir or ".").expanduser()
        project_file = project_dir / "dbt_project.yml"
        try:
            with project_file.open("r") as project_yaml:
                project_config = yaml.safe_load(project_yaml) or {}
        except FileNotFoundError as exc:
            raise ValueError(
                "airflow.operator='dbt' requires airflow.dbt_profile or a readable "
                f"'profile' in {project_file}"
            ) from exc
        except yaml.YAMLError as exc:
            raise ValueError(
                f"Could not parse dbt project configuration {project_file}: {exc}"
            ) from exc

        if not isinstance(project_config, dict):
            raise ValueError(f"dbt project configuration {project_file} must be a YAML mapping")

        profile = project_config.get("profile")
        if not isinstance(profile, str) or not profile.strip():
            raise ValueError(
                "airflow.operator='dbt' requires airflow.dbt_profile or a non-empty "
                f"'profile' in {project_file}"
            )
        return profile

    def _profiles_yml_path_expression(self) -> str:
        """Return a Python expression for the configured/default profiles.yml path."""
        if self.config.dbt_profiles_dir:
            profiles_dir = self.config.dbt_profiles_dir
            if profiles_dir.startswith("~"):
                return (
                    f"str(Path({self._python_literal(profiles_dir)}).expanduser() "
                    '/ "profiles.yml")'
                )
            return self._python_literal(str(Path(profiles_dir) / "profiles.yml"))
        return 'str(Path.home() / ".dbt" / "profiles.yml")'

    @staticmethod
    def _python_literal(value: Any) -> str:
        """Return a source-safe Python literal for a generated DAG."""
        return repr(value)

    def _cosmos_task_lines(
        self, task_id: str, command: str, pool: Optional[str] = None
    ) -> List[str]:
        """Render a Cosmos local operator while retaining the generated dbt flags."""
        argv = shlex.split(command)
        if len(argv) < 2 or argv[0] != "dbt":
            raise ValueError(f"Cannot map generated command to a Cosmos dbt operator: {command}")

        operator_by_command = {
            "build": "DbtBuildLocalOperator",
            "run": "DbtRunLocalOperator",
            "seed": "DbtSeedLocalOperator",
            "snapshot": "DbtSnapshotLocalOperator",
            "test": "DbtTestLocalOperator",
        }
        command_name = argv[1]
        operator = operator_by_command.get(command_name)
        if operator is None:
            raise ValueError(
                f"Unsupported dbt command '{command_name}' for airflow.operator='dbt'. "
                f"Supported commands: {', '.join(sorted(operator_by_command))}"
            )

        # Cosmos configures project, profile and target independently. dbt
        # exposes --threads on individual commands, so retain it alongside
        # selector and full-refresh command flags.
        command_flags: List[str] = []
        index = 2
        runtime_flags = {"--project-dir", "--profiles-dir", "--target"}
        while index < len(argv):
            flag = argv[index]
            if flag in runtime_flags:
                index += 1
                while index < len(argv) and not argv[index].startswith("--"):
                    index += 1
                continue
            command_flags.append(flag)
            index += 1

        task_var = self._safe_var(task_id)
        project_dir = self.config.dbt_project_dir or "."
        if project_dir.startswith("~"):
            project_dir_expression = f"str(Path({self._python_literal(project_dir)}).expanduser())"
        else:
            project_dir_expression = self._python_literal(project_dir)
        lines = [
            f"    {task_var} = {operator}(",
            f'        task_id="{task_id}",',
            f"        project_dir={project_dir_expression},",
            "        profile_config=profile_config,",
            "        install_deps=False,",
            "        append_env=True,",
        ]
        if command_flags:
            lines.append(f"        dbt_cmd_flags={self._python_literal(command_flags)},")
        if pool:
            lines.append(f'        pool="{pool}",')
        lines += ["    )", ""]
        return lines

    def _lineage_task_lines(
        self,
        lineage: Tuple[List[str], List[Tuple[str, str]]],
        task_groups: List[List[Tuple[str, str]]],
    ) -> List[str]:
        """Render the visual-only lineage TaskGroup."""
        models, edges = lineage
        lines = [
            "    # Visual only: the dbt graph inside this selector. EmptyOperators, so",
            "    # no dbt process and no warehouse work happens here. They all succeed",
            "    # together when the single dbt build above finishes - this shows the",
            "    # shape of the graph, not per-model status.",
            '    with TaskGroup(group_id="lineage") as lineage:',
            "        lineage_nodes = {}",
        ]
        for model in models:
            meta = self._model_index[model]
            lines += [
                f'        lineage_nodes["{model}"] = EmptyOperator(',
                f'            task_id="{model}",',
                f'            task_display_name="{model}  ({meta["materialized"]})",',
                "        )",
            ]
        if edges:
            lines.append("")
            for parent, child in edges:
                lines.append(f'        lineage_nodes["{parent}"] >> lineage_nodes["{child}"]')
        # Hang the picture off the dbt task(s) so it reads left-to-right in the UI.
        last_tasks = [self._safe_var(group[-1][0]) for group in task_groups]
        lines.append("")
        if len(last_tasks) == 1:
            lines.append(f"    {last_tasks[0]} >> lineage")
        else:
            lines.append(f"    [{', '.join(last_tasks)}] >> lineage")
        lines.append("")
        return lines

    def _lineage_doc_lines(
        self,
        lineage: Tuple[List[str], List[Tuple[str, str]]],
        selector_name: str,
    ) -> List[str]:
        """Render the LINEAGE_DOC markdown shown in the Airflow docs panel."""
        models, edges = lineage
        counts: Dict[str, int] = {}
        for model in models:
            mat = self._model_index[model]["materialized"]
            counts[mat] = counts.get(mat, 0) + 1
        summary = ", ".join(f"{n} {mat}" for mat, n in sorted(counts.items()))

        doc = [
            f"### `{selector_name}`",
            "",
            f"One `dbt build --selector {selector_name}` builds these "
            f"{len(models)} models ({summary}).",
            "",
            "The `lineage` task group is a **picture of the dbt graph** - "
            "EmptyOperators, not dbt runs.",
            "They all go green when the single build finishes, so they do **not** "
            "report per-model status.",
            "",
            "| model | materialization | relation |",
            "|---|---|---|",
        ]
        for model in models:
            meta = self._model_index[model]
            doc.append(f"| `{model}` | {meta['materialized']} | `{meta['relation']}` |")
        if edges:
            doc += ["", f"{len(edges)} dependency edge(s) within the selector."]

        # Escape only what would break the generated triple-quoted string.
        body = "\n".join(doc).replace("\\", "\\\\").replace('"""', '\\"\\"\\"')
        return [f'LINEAGE_DOC = """{body}\n"""']

    # ------------------------------------------------------------------
    # Idempotency helpers
    # ------------------------------------------------------------------

    def _is_generated_file(self, path: str) -> bool:
        """Return True if a file was produced by maestro (current or legacy)."""
        try:
            with open(path, "r") as f:
                head = f.read(512)
        except OSError:
            return False
        return GENERATED_PHRASE in head
