"""Generate Airflow DAG Python files from dbt selectors.

Mirrors the dbt Cloud job generator: maestro emits ONE DAG file per selector
(the Airflow analogue of one job per selector). Each DAG gets its own schedule,
SLA and retry policy. Generation is idempotent - every auto-generated file
carries a marker comment and is rebuilt on each run; stale auto-generated files
are removed, while hand-written DAGs are left untouched.
"""

import os
import re
from datetime import datetime
from typing import Any, Dict, List, Optional, Tuple

from dbt_job_maestro.config import AirflowConfig, CustomFullRefreshSchedule
from dbt_job_maestro.selector_types import count_fqn_models

# Marker written into every generated file. Used to recognise (and safely
# overwrite / clean up) maestro-owned DAGs without touching hand-written ones.
GENERATED_MARKER = "# Auto-generated by dbt-job-maestro - DO NOT EDIT"

# Looser phrase present in BOTH the current marker and the docstring of files
# produced by older maestro versions. Cleanup detects this so regenerating also
# removes legacy single-DAG files (e.g. an old dbt_maestro_dag.py).
GENERATED_PHRASE = "Auto-generated by dbt-job-maestro"


class AirflowDAGGenerator:
    """Generate one Airflow DAG file per selector from selectors.yml."""

    def __init__(
        self,
        config: AirflowConfig,
        manifest_data: Optional[Dict[str, Any]] = None,
    ):
        # manifest_data is accepted for API compatibility but no longer used:
        # one-DAG-per-selector cannot wire cross-selector dependencies.
        self.config = config
        self.manifest_data = manifest_data

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def generate_dags(self, selectors: List[Dict[str, Any]]) -> Dict[str, str]:
        """Generate DAG files from selectors.

        Args:
            selectors: Selector definitions loaded from selectors.yml.

        Returns:
            Mapping of ``filename -> python_source`` for each generated DAG.
        """
        prefix = f"{self.config.selector_prefix}_"
        full_refresh_selector_name = f"{self.config.selector_prefix}_full_refresh_incremental"

        # Drop freshness selectors and the full-refresh selector (handled below).
        candidates = [
            s
            for s in selectors
            if not s["name"].startswith("freshness_")
            and not s["name"].startswith("automatically_generated_freshness_")
            and s["name"] != full_refresh_selector_name
        ]

        # Apply maestro/manual inclusion settings.
        filtered: List[Dict[str, Any]] = []
        for sel in candidates:
            is_auto = sel["name"].startswith(prefix)
            if is_auto and not self.config.include_maestro_selectors_in_dags:
                continue
            if not is_auto and not self.config.include_manual_selectors_in_dags:
                continue
            filtered.append(sel)

        if self.config.execution_order:
            filtered = self._sort_by_execution_order(filtered)

        # Partition into "large" (own DAG) and "small" (combined) selectors.
        large, small = self._partition_by_size(filtered, prefix)

        dags: Dict[str, str] = {}
        dag_index = 0

        for sel in large:
            name = sel["name"]
            is_manual = not name.startswith(prefix)
            dag_id = self._dag_id_for(name)
            schedule = self._schedule_for(is_manual, dag_index)
            sla = self._sla_for(is_manual)
            tasks = [(self._task_id(name), self._get_dbt_command(sel))]
            dags[f"{dag_id}.py"] = self._render_dag(dag_id, schedule, sla, tasks)
            dag_index += 1

        if small:
            dag_id = f"{self.config.dag_id_prefix}_combined_small_selectors"
            schedule = self._schedule_for(False, dag_index)
            sla = self._sla_for(False)
            tasks = [(self._task_id(s["name"]), self._get_dbt_command(s)) for s in small]
            dags[f"{dag_id}.py"] = self._render_dag(dag_id, schedule, sla, tasks, chain=True)
            dag_index += 1

        # Full-refresh DAGs (each its own file with its own cron).
        dags.update(self._generate_full_refresh_dags())

        return dags

    def write_dags(self, dags: Dict[str, str], dags_dir: str) -> Tuple[List[str], List[str]]:
        """Write generated DAGs to a directory, idempotently.

        Writes/overwrites every file in ``dags``, then deletes any *other*
        ``.py`` file in the directory that carries the generated marker (a stale
        auto-generated DAG no longer backed by a selector). Files without the
        marker (hand-written DAGs) are never touched.

        Args:
            dags: Mapping of filename -> python source.
            dags_dir: Destination directory.

        Returns:
            Tuple of (written filenames, removed filenames).
        """
        os.makedirs(dags_dir or ".", exist_ok=True)

        written = sorted(dags.keys())
        for filename, source in dags.items():
            with open(os.path.join(dags_dir, filename), "w") as f:
                f.write(source)

        removed: List[str] = []
        for existing in os.listdir(dags_dir):
            if not existing.endswith(".py") or existing in dags:
                continue
            path = os.path.join(dags_dir, existing)
            if not os.path.isfile(path):
                continue
            if self._is_generated_file(path):
                os.remove(path)
                removed.append(existing)

        return written, sorted(removed)

    # ------------------------------------------------------------------
    # Selector classification & dbt command helpers
    # ------------------------------------------------------------------

    def _get_selector_type(self, selector_name: str) -> str:
        """Classify a selector as 'seeds', 'snapshots', 'full_refresh', or 'models'."""
        prefix = self.config.selector_prefix
        if selector_name == f"{prefix}_seeds" or selector_name.endswith("_seeds"):
            return "seeds"
        if selector_name == f"{prefix}_snapshots" or selector_name.endswith("_snapshots"):
            return "snapshots"
        if selector_name.endswith("_full_refresh_incremental"):
            return "full_refresh"
        return "models"

    def _get_dbt_command(self, selector: Dict[str, Any]) -> str:
        """Build the dbt CLI invocation for a selector."""
        name = selector["name"]
        sel_type = self._get_selector_type(name)

        if sel_type == "seeds":
            parts = ["dbt", "seed"]
        elif sel_type == "snapshots":
            parts = ["dbt", "snapshot"]
        elif sel_type == "full_refresh":
            parts = ["dbt", "build", "--full-refresh"]
        else:
            parts = ["dbt", "build"]

        parts += ["--selector", name]
        parts += self._dbt_runtime_flags()
        return " ".join(parts)

    def _dbt_runtime_flags(self) -> List[str]:
        """Common --project-dir/--profiles-dir/--target/--threads flags."""
        flags: List[str] = []
        if self.config.dbt_project_dir:
            flags += ["--project-dir", self.config.dbt_project_dir]
        if self.config.dbt_profiles_dir:
            flags += ["--profiles-dir", self.config.dbt_profiles_dir]
        if self.config.dbt_target:
            flags += ["--target", self.config.dbt_target]
        if self.config.dbt_threads:
            flags += ["--threads", str(self.config.dbt_threads)]
        return flags

    # ------------------------------------------------------------------
    # Partitioning, ordering, naming
    # ------------------------------------------------------------------

    def _partition_by_size(
        self, selectors: List[Dict[str, Any]], prefix: str
    ) -> Tuple[List[Dict[str, Any]], List[Dict[str, Any]]]:
        """Split selectors into (large=own DAG, small=combined).

        Only auto-generated (maestro) selectors with a positive model count
        below min_models_per_dag are "small". Manual selectors and non-model
        resources always get their own DAG.
        """
        if self.config.min_models_per_dag <= 1:
            return selectors, []

        large: List[Dict[str, Any]] = []
        small: List[Dict[str, Any]] = []
        for sel in selectors:
            is_auto = sel["name"].startswith(prefix)
            if not is_auto or self._get_selector_type(sel["name"]) != "models":
                large.append(sel)
                continue
            count = count_fqn_models(sel)
            if 0 < count < self.config.min_models_per_dag:
                small.append(sel)
            else:
                large.append(sel)
        return large, small

    def _sort_by_execution_order(self, selectors: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
        """Order selectors by configured resource-type execution_order."""
        order = {rt: i for i, rt in enumerate(self.config.execution_order)}
        default = len(self.config.execution_order)

        def key(sel: Dict[str, Any]) -> Tuple[int, str]:
            rt = self._get_selector_type(sel["name"])
            # full_refresh isn't an execution_order value; treat it like models.
            lookup = "models" if rt == "full_refresh" else rt
            return (order.get(lookup, default), sel["name"])

        return sorted(selectors, key=key)

    def _dag_id_for(self, selector_name: str) -> str:
        """Build a DAG id from a selector name."""
        return f"{self.config.dag_id_prefix}_{selector_name}"

    def _task_id(self, selector_name: str) -> str:
        """Airflow task_id for a selector's task (hyphens/dots are valid here)."""
        return f"run_{selector_name}"

    @staticmethod
    def _safe_var(task_id: str) -> str:
        """Turn a task_id into a valid Python variable name.

        Selector names may contain characters that are legal in Airflow
        task_ids/dag_ids (e.g. '-', '.') but not in Python identifiers, which
        would otherwise produce a SyntaxError in the generated assignment.
        """
        var = re.sub(r"\W", "_", task_id)
        if var and var[0].isdigit():
            var = f"_{var}"
        return var

    # ------------------------------------------------------------------
    # Schedule & SLA resolution
    # ------------------------------------------------------------------

    def _schedule_for(self, is_manual: bool, dag_index: int) -> Optional[str]:
        """Resolve the cron schedule for a DAG (None = no schedule)."""
        if self.config.orchestration_mode == "none":
            return None
        if is_manual and self.config.manual_schedule_interval:
            return self.config.manual_schedule_interval
        if self.config.orchestration_mode == "staggered":
            return self._staggered_cron(dag_index)
        return self.config.schedule_interval

    def _sla_for(self, is_manual: bool) -> int:
        """Resolve the SLA in minutes for a DAG (0 = no SLA)."""
        if is_manual and self.config.manual_sla_minutes >= 0:
            return self.config.manual_sla_minutes
        return self.config.sla_minutes

    def _staggered_cron(self, dag_index: int) -> str:
        """Cron offset by cron_increment_minutes per DAG from the start time."""
        total = (
            self.config.start_hour * 60
            + self.config.start_minute
            + dag_index * self.config.cron_increment_minutes
        )
        hour = (total // 60) % 24
        minute = total % 60

        if self.config.cron_days_of_week:
            day_map = {
                "SUN": "0",
                "MON": "1",
                "TUE": "2",
                "WED": "3",
                "THU": "4",
                "FRI": "5",
                "SAT": "6",
            }
            days = ",".join(day_map.get(d.upper(), "*") for d in self.config.cron_days_of_week)
        else:
            days = "*"

        return f"{minute} {hour} * * {days}"

    # ------------------------------------------------------------------
    # Full refresh DAGs
    # ------------------------------------------------------------------

    def _generate_full_refresh_dags(self) -> Dict[str, str]:
        """Build the full-refresh / seeds-full-refresh DAGs."""
        dags: Dict[str, str] = {}
        fr = self.config.full_refresh

        if fr.enabled:
            dag_id = f"{self.config.dag_id_prefix}_full_refresh_incremental"
            selector = f"{self.config.selector_prefix}_full_refresh_incremental"
            cmd = " ".join(
                ["dbt", "build", "--full-refresh", "--selector", selector]
                + self._dbt_runtime_flags()
            )
            tasks = [(self._task_id(selector), cmd)]
            dags[f"{dag_id}.py"] = self._render_dag(dag_id, fr.cron_schedule, 0, tasks)

        for schedule in fr.custom_schedules:
            if not schedule.name:
                continue
            cmd = self._custom_full_refresh_command(schedule)
            if not cmd:
                continue
            dag_id = f"{self.config.dag_id_prefix}_full_refresh_{schedule.name}"
            tasks = [(f"run_full_refresh_{schedule.name}", cmd)]
            dags[f"{dag_id}.py"] = self._render_dag(dag_id, schedule.cron_schedule, 0, tasks)

        if self.config.seeds_full_refresh.enabled:
            dag_id = f"{self.config.dag_id_prefix}_seeds_full_refresh"
            selector = f"{self.config.selector_prefix}_seeds"
            cmd = " ".join(
                ["dbt", "seed", "--full-refresh", "--selector", selector]
                + self._dbt_runtime_flags()
            )
            tasks = [(self._task_id(selector), cmd)]
            dags[f"{dag_id}.py"] = self._render_dag(
                dag_id, self.config.seeds_full_refresh.cron_schedule, 0, tasks
            )

        return dags

    def _custom_full_refresh_command(self, schedule: CustomFullRefreshSchedule) -> Optional[str]:
        """Build the dbt command for a custom full-refresh schedule."""
        if schedule.selector:
            parts = ["dbt", "build", "--full-refresh", "--selector", schedule.selector]
        elif schedule.tags:
            selects = " ".join(f"tag:{t}" for t in schedule.tags)
            parts = ["dbt", "build", "--full-refresh", "--select", selects]
        elif schedule.paths:
            selects = " ".join(f"path:{p}" for p in schedule.paths)
            parts = ["dbt", "build", "--full-refresh", "--select", selects]
        elif schedule.models:
            selects = " ".join(schedule.models)
            parts = ["dbt", "build", "--full-refresh", "--select", selects]
        else:
            return None
        return " ".join(parts + self._dbt_runtime_flags())

    # ------------------------------------------------------------------
    # Rendering
    # ------------------------------------------------------------------

    def _render_dag(
        self,
        dag_id: str,
        schedule_interval: Optional[str],
        sla_minutes: int,
        tasks: List[Tuple[str, str]],
        chain: bool = False,
    ) -> str:
        """Render a single DAG file.

        Args:
            dag_id: Airflow DAG id.
            schedule_interval: Cron string, or None for manual-trigger DAGs.
            sla_minutes: Task SLA in minutes (0 = no SLA).
            tasks: List of (task_id, bash_command).
            chain: If True, wire tasks sequentially (used for combined DAGs).
        """
        lines: List[str] = [
            '"""',
            "Auto-generated by dbt-job-maestro.",
            "DO NOT EDIT - regenerate with: maestro generate-dags",
            '"""',
            GENERATED_MARKER,
            "",
            "from datetime import datetime, timedelta",
            "",
            "from airflow import DAG",
            "from airflow.operators.bash import BashOperator",
            "",
            "",
        ]

        # default_args
        lines += [
            "default_args = {",
            f'    "owner": "{self.config.owner}",',
            '    "depends_on_past": False,',
            '    "email_on_failure": False,',
            f'    "retries": {self.config.retries},',
            f'    "retry_delay": timedelta(minutes={self.config.retry_delay_minutes}),',
        ]
        if sla_minutes > 0:
            lines.append(f'    "sla": timedelta(minutes={sla_minutes}),')
        lines += ["}", "", ""]

        # DAG context
        try:
            dt = datetime.strptime(self.config.start_date, "%Y-%m-%d")
            start_date_expr = f"datetime({dt.year}, {dt.month}, {dt.day})"
        except ValueError:
            start_date_expr = "datetime(2024, 1, 1)"

        schedule_expr = f'"{schedule_interval}"' if schedule_interval is not None else "None"

        lines += [
            "with DAG(",
            f'    dag_id="{dag_id}",',
            "    default_args=default_args,",
            f"    schedule_interval={schedule_expr},",
            f"    start_date={start_date_expr},",
            "    catchup=False,",
            f"    tags={repr(self.config.tags)},",
            ") as dag:",
            "",
        ]

        # Tasks. task_id keeps the (possibly hyphenated) selector name; the
        # Python variable is sanitised so the assignment is always valid.
        for task_id, cmd in tasks:
            task_var = self._safe_var(task_id)
            lines += [
                f"    {task_var} = BashOperator(",
                f'        task_id="{task_id}",',
                f'        bash_command="{cmd}",',
                "    )",
                "",
            ]

        # Chain tasks sequentially for combined DAGs (mirrors a job's ordered
        # execute_steps). Single-task DAGs need no dependency lines.
        if chain and len(tasks) > 1:
            lines.append("    # Run combined selectors in order")
            chain_expr = " >> ".join(self._safe_var(task_id) for task_id, _ in tasks)
            lines.append(f"    {chain_expr}")
            lines.append("")

        return "\n".join(lines) + "\n"

    # ------------------------------------------------------------------
    # Idempotency helpers
    # ------------------------------------------------------------------

    def _is_generated_file(self, path: str) -> bool:
        """Return True if a file was produced by maestro (current or legacy)."""
        try:
            with open(path, "r") as f:
                head = f.read(512)
        except OSError:
            return False
        return GENERATED_PHRASE in head
